INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Afghanistan','AF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Åland Islands','AX');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Albania','AL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Algeria','DZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('American Samoa','AS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Andorra','AD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Angola','AO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Anguilla','AI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Antarctica','AQ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Antigua and Barbuda','AG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Argentina','AR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Armenia','AM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Aruba','AW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Australia','AU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Austria','AT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Azerbaijan','AZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bahamas','BS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bahrain','BH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bangladesh','BD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Barbados','BB');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Belarus','BY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Belgium','BE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Belize','BZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Benin','BJ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bermuda','BM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bhutan','BT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bolivia','BO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bonaire','BQ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bosnia and Herzegovina','BA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Botswana','BW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bouvet Island','BV');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Brazil','BR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('British Indian Ocean Territory','IO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Brunei Darussalam','BN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Bulgaria','BG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Burkina Faso','BF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Burundi','BI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cambodia','KH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cameroon','CM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Canada','CA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cape Verde','CV');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cayman Islands','KY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Central African Republic','CF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Chad','TD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Chile','CL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('China','CN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Christmas Island','CX');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cocos (Keeling) Islands','CC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Colombia','CO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Comoros','KM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Congo','CG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Congo, the Democratic Republic of the','CD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cook Islands','CK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Costa Rica','CR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Côte d''Ivoire','CI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Croatia','HR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cuba','CU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Curaçao','CW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Cyprus','CY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Czech Republic','CZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Denmark','DK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Djibouti','DJ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Dominica','DM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Dominican Republic','DO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Ecuador','EC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Egypt','EG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('El Salvador','SV');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Equatorial Guinea','GQ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Eritrea','ER');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Estonia','EE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Ethiopia','ET');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Falkland Islands (Malvinas)','FK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Faroe Islands','FO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Fiji','FJ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Finland','FI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('France','FR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('French Guiana','GF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('French Polynesia','PF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('French Southern Territories','TF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Gabon','GA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Gambia','GM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Georgia','GE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Germany','DE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Ghana','GH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Gibraltar','GI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Greece','GR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Greenland','GL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Grenada','GD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guadeloupe','GP');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guam','GU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guatemala','GT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guernsey','GG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guinea','GN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guinea-Bissau','GW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Guyana','GY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Haiti','HT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Heard Island and McDonald Islands','HM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Holy See (Vatican City State)','VA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Honduras','HN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Hong Kong','HK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Hungary','HU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Iceland','IS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('India','IN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Indonesia','ID');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Iran','IR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Iraq','IQ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Ireland','IE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Isle of Man','IM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Israel','IL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Italy','IT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Jamaica','JM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Japan','JP');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Jersey','JE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Jordan','JO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Kazakhstan','KZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Kenya','KE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Kiribati','KI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Korea, Democratic People''s Republic of','KP');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Korea, Republic of','KR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Kuwait','KW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Kyrgyzstan','KG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Lao People''s Democratic Republic','LA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Latvia','LV');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Lebanon','LB');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Lesotho','LS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Liberia','LR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Libya','LY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Liechtenstein','LI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Lithuania','LT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Luxembourg','LU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Macao','MO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Macedonia','MK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Madagascar','MG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Malawi','MW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Malaysia','MY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Maldives','MV');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mali','ML');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Malta','MT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Marshall Islands','MH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Martinique','MQ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mauritania','MR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mauritius','MU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mayotte','YT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mexico','MX');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Micronesia, Federated States of','FM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Moldova, Republic of','MD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Monaco','MC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mongolia','MN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Montenegro','ME');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Montserrat','MS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Morocco','MA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Mozambique','MZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Myanmar','MM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Namibia','NA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Nauru','NR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Nepal','NP');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Netherlands','NL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('New Caledonia','NC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('New Zealand','NZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Nicaragua','NI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Niger','NE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Nigeria','NG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Niue','NU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Norfolk Island','NF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Northern Mariana Islands','MP');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Norway','NO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Oman','OM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Pakistan','PK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Palau','PW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Palestine','PS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Panama','PA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Papua New Guinea','PG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Paraguay','PY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Peru','PE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Philippines','PH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Pitcairn','PN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Poland','PL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Portugal','PT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Puerto Rico','PR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Qatar','QA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Réunion','RE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Romania','RO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Russian Federation','RU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Rwanda','RW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Barthélemy','BL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Helena, Ascension and Tristan da Cunha','SH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Kitts and Nevis','KN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Lucia','LC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Martin (French part)','MF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Pierre and Miquelon','PM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saint Vincent and the Grenadines','VC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Samoa','WS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('San Marino','SM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Sao Tome and Principe','ST');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Saudi Arabia','SA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Senegal','SN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Serbia','RS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Seychelles','SC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Sierra Leone','SL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Singapore','SG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Sint Maarten (Dutch part)','SX');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Slovakia','SK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Slovenia','SI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Solomon Islands','SB');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Somalia','SO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('South Africa','ZA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('South Georgia and the South Sandwich Islands','GS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('South Sudan','SS');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Spain','ES');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Sri Lanka','LK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Sudan','SD');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Suriname','SR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Svalbard and Jan Mayen','SJ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Swaziland','SZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Sweden','SE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Switzerland','CH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Syrian Arab Republic','SY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Taiwan','TW');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Tajikistan','TJ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Tanzania','TZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Thailand','TH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Timor-Leste','TL');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Togo','TG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Tokelau','TK');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Tonga','TO');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Trinidad and Tobago','TT');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Tunisia','TN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Turkey','TR');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Turkmenistan','TM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Turks and Caicos Islands','TC');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Tuvalu','TV');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Uganda','UG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Ukraine','UA');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('United Arab Emirates','AE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('United Kingdom','GB');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('United States','US');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('United States Minor Outlying Islands','UM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Uruguay','UY');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Uzbekistan','UZ');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Vanuatu','VU');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Venezuela, Bolivarian Republic of','VE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Viet Nam','VN');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Virgin Islands, British','VG');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Virgin Islands, U.S.','VI');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Wallis and Futuna','WF');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Western Sahara','EH');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Yemen','YE');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Zambia','ZM');
INSERT INTO [dbo].[Countries] ([Name],[Code]) VALUES('Zimbabwe','ZW');
